from lenora_backend.testing.conformance import AdapterConformance
from lenora_adapter_template import TemplateAdapter, TemplateSettings

class TestTemplateConformance(AdapterConformance):
    adapter_cls = TemplateAdapter
    settings = TemplateSettings(api_key="test")

    def upload_request(self, model): ...
    def job_request(self, model, asset_ref): ...
    def mock_running(self, router): ...
    def mock_succeeded(self, router): ...
    def mock_failed(self, router): ...
    def mock_unreachable(self, router): ...
